### ISSUE TITLE
<feature> AST实现

### ISSUE THREAD

**Issue by ll06printf** [sfinae687/SysYust#17]
根据文档 [AST 数据结构设计](https://hackmd.io/nWZzINQoTZizzrYg3mvuaw) 实现一个独立的抽象语法树。

- [ ] #28
- [ ] #22

**Comment by l3773l** [comment]
啊这，什么时候改的😵‍💫

**Comment by ll06printf** [comment]
语法树基类和CRTR基类.

- [ ] Node
- [ ] NodeBase<D>

**Comment by l3773l** [comment]
CRTR 又是什么东西😵‍💫

**Comment by ll06printf** [comment]
> CRTR 又是什么东西😵‍💫

就是奇异重现递归模板模式,为了少写几行派生类代码().

**Comment by ll06printf** [comment]
> CRTR 又是什么东西😵‍💫

可参考我的这个提交 15f9fe7214acecf4967869bccda130d55b8f8557

**Comment by l3773l** [comment]
不是叫 CRTP 吗🤔



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月31日(Fri) Noon1:59
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sfinae687/SysYust] <feature&gt; AST实现 (Issue #17)




  
CRTR 又是什么东西😵‍💫
  
就是奇异重现递归模板模式,为了少写几行派生类代码().

**Comment by ll06printf** [comment]
> 不是叫 CRTP 吗🤔
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2024年5月31日(Fri) Noon1:59 To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [sfinae687/SysYust] <feature&gt; AST实现 (Issue #17) CRTR 又是什么东西😵‍💫 就是奇异重现递归模板模式,为了少写几行派生类代码(). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

太久没打记错名字了()
