### ISSUE TITLE
<feature> 提取脚本

### ISSUE THREAD

**Issue by ll06printf** [sfinae687/SysYust#19]
制作一个脚本，将所有需要提交到代码提交平台的代码提取出来。

- [ ] 制作需要提交的文件名单
- [ ] 决定提取脚本的语法
- [ ] 编写制作脚本
- [ ] 添加github action(可选).

**Comment by l3773l** [comment]
\<request\> 测试脚本
- [ ] 导入比赛给定的功能测试。
- [ ] 模拟编译环境，使用比赛提供的 Compiler.js 进行编译。

**Comment by ll06printf** [comment]
需要提交的文件目录

- include/*
- src/* (但是排除generated下的头文件)
- 排除所有的CMakeLists.txt文件
- REDEAME.md （可能需要重写一份）

按照与储存库目录相同的相对路径导出
