### ISSUE TITLE
重构、整理与协调

### ISSUE THREAD

**Issue by l3773l** [sfinae687/SysYust#64]
- [x] indexOf 的行为

# IR

**Comment by l3773l** [comment]
关于 indexOf 的行为：
目前 indexOf 的行为规定有缺陷，无法区分数组 ptr 和参数 decay 一维所产生的 ptr。

提案：
第一种：增加 ptrindexOf 接受指针得到解引用的指针，IR 生成 在解引用层数不匹配的时候加入。
第二种：类型中加入缺省维度值 [? x [3 x i32]] 代指未知的维度长度，IR 生成在 特别匹配到参数指针时加入。

**Comment by ll06printf** [comment]
目前 indexOf 接受一个数组或指针参数, 和一组表示索引的整数, 返回一个指针, 它的子类型是数组或指针的第 *索引个数* 层深的子类型.

**Comment by ll06printf** [comment]
> 关于 indexOf 的行为：
> 目前 indexOf 的行为规定有缺陷，无法区分数组 ptr 和参数 decay 一维所产生的 ptr。
> 
> 提案：
> 第一种：增加 ptrindexOf 接受指针得到解引用的指针，IR 生成 在解引用层数不匹配的时候加入。
> 第二种：类型中加入缺省维度值 [? x [3 x i32]] 代指未知的维度长度，IR 生成在 特别匹配到参数指针时加入。

类型系统上似乎就不能分辨两种情况。

**Comment by ll06printf** [comment]
两种修改方案，一种意味着需要在创建indexOf是有手段分辨两种情况，另一种意味着需要修改类型系统和参数传递相关的代码。
